"""One-command team bootstrap — charter join <token>.

Decodes a self-contained invite token, creates identity if needed,
joins the team, and scaffolds a network node. One command to go from
zero to team member.

Usage:
    charter join <invite_token>

The token is generated by `charter team invite` and can be shared
via email, WhatsApp, text, or any messaging channel.
"""

import base64
import json
import os
import sys
import time


def decode_invite_token(token_string):
    """Decode an invite token into payload and signature.

    Token format: base64url(JSON_payload).hmac_hex

    Returns dict with keys: payload (dict), signature (str)
    Raises ValueError on invalid format.
    """
    if not token_string or not token_string.strip():
        raise ValueError("Empty token")

    token_string = token_string.strip()
    parts = token_string.split(".")
    if len(parts) != 2:
        raise ValueError("Invalid token format: expected payload.signature")

    b64_payload, sig = parts

    # Add back base64 padding
    padding = 4 - len(b64_payload) % 4
    if padding != 4:
        b64_payload += "=" * padding

    try:
        payload_bytes = base64.urlsafe_b64decode(b64_payload)
    except Exception:
        raise ValueError("Token payload is not valid base64")

    try:
        payload = json.loads(payload_bytes)
    except json.JSONDecodeError:
        raise ValueError("Token payload is not valid JSON")

    return {"payload": payload, "signature": sig}


def validate_token(payload):
    """Validate token payload fields and expiry.

    Returns (valid: bool, reason: str).
    """
    version = payload.get("v")
    if version != 1:
        return (False, "Unsupported token version: {}. Update Charter.".format(version))

    required = ["th", "tn", "e", "n", "r", "ib", "ia"]
    for key in required:
        if not payload.get(key):
            return (False, "Missing required field: {}".format(key))

    # Validate team hash format (64 hex chars)
    th = payload["th"]
    if len(th) != 64:
        return (False, "Invalid team hash length: {}".format(len(th)))
    try:
        int(th, 16)
    except ValueError:
        return (False, "Invalid team hash: not hexadecimal")

    # Check expiry
    expiry = payload.get("x")
    if expiry:
        try:
            exp_time = time.strptime(expiry, "%Y-%m-%dT%H:%M:%SZ")
            if time.mktime(exp_time) < time.time():
                return (False, "Token expired on {}".format(expiry))
        except ValueError:
            pass  # Non-standard expiry format, skip check

    return (True, "ok")


def run_join(token_string):
    """Execute charter join — one-command team bootstrap.

    Steps:
        1. Decode and validate the invite token
        2. Create identity if none exists
        3. Create team directory and write team.json
        4. Write invite + accept events to members.jsonl
        5. Initialize team chain
        6. Log to global chain
        7. Create network node scaffold
        8. Print welcome summary
    """
    # Step 1: Decode and validate
    try:
        decoded = decode_invite_token(token_string)
    except ValueError as e:
        print("Invalid token: {}".format(e))
        sys.exit(1)

    payload = decoded["payload"]
    valid, reason = validate_token(payload)
    if not valid:
        print("Token rejected: {}".format(reason))
        sys.exit(1)

    team_hash = payload["th"]
    team_name = payload["tn"]

    print()
    print("Joining team: {}".format(team_name))
    print("-" * 40)

    # Step 2: Identity (idempotent)
    from charter.identity import load_identity, create_identity, append_to_chain

    identity = load_identity()
    if identity:
        print("  Identity:  {} (existing)".format(identity["alias"]))
    else:
        alias = payload["n"].lower().replace(" ", "-")
        identity = create_identity(alias=alias)
        print("  Identity:  {} (created)".format(identity["alias"]))

    # Step 3: Team directory (idempotent)
    from charter.team import (
        get_team_dir, load_team, get_members,
        _hash_entry, _sign_entry, _log_member_event,
        _append_to_team_chain, _update_team_manifest,
    )

    team_dir = get_team_dir(team_hash)
    existing_team = load_team(team_hash)

    if existing_team:
        print("  Team:      {} (exists locally)".format(existing_team["name"]))
        # Check if already a member
        members = get_members(team_hash)
        already_member = any(
            m.get("member_id") == identity["public_id"]
            for m in members
        )
        if already_member:
            print()
            print("You are already a member of {}.".format(team_name))
            print("Run 'charter team status' to see details.")
            return
    else:
        os.makedirs(team_dir, exist_ok=True)

        now = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
        manifest = {
            "version": "1.0",
            "team_hash": team_hash,
            "name": team_name,
            "alias": "team-{}".format(team_hash[:8]),
            "created_by": payload["ib"],
            "created_at": payload["ia"],
            "member_count": 0,
            "joined_via": "invite_token",
            "joined_at": now,
        }
        with open(os.path.join(team_dir, "team.json"), "w") as f:
            json.dump(manifest, f, indent=2)
        print("  Team:      {} (created locally)".format(team_name))

    # Step 4: Write membership events
    now = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    members_path = os.path.join(team_dir, "members.jsonl")

    invite_event = {
        "event": "invite",
        "member_id": None,
        "name": payload["n"],
        "email": payload["e"],
        "role": payload["r"],
        "invited_by": payload["ib"],
        "timestamp": payload["ia"],
    }

    accept_event = {
        "event": "accept",
        "member_id": identity["public_id"],
        "name": payload["n"],
        "email": payload["e"],
        "accepted_at": now,
    }

    if not os.path.isfile(members_path):
        with open(members_path, "w") as f:
            f.write(json.dumps(invite_event) + "\n")
            f.write(json.dumps(accept_event) + "\n")
    else:
        _log_member_event(team_hash, accept_event)

    print("  Membership: accepted")

    # Step 5: Initialize or append to team chain
    chain_path = os.path.join(team_dir, "chain.jsonl")
    if not os.path.isfile(chain_path):
        genesis = {
            "index": 0,
            "timestamp": now,
            "event": "joined_via_token",
            "data": {
                "team_hash": team_hash,
                "team_name": team_name,
                "member_id": identity["public_id"],
                "invited_by": payload["ib"],
                "role": payload["r"],
                "token_signature": decoded["signature"],
            },
            "previous_hash": "0" * 64,
            "signer": identity["public_id"],
        }
        genesis["hash"] = _hash_entry(genesis)
        genesis["signature"] = _sign_entry(genesis, identity["private_seed"])
        with open(chain_path, "w") as f:
            f.write(json.dumps(genesis) + "\n")
    else:
        _append_to_team_chain(team_hash, "member_accepted", {
            "member_id": identity["public_id"],
            "name": payload["n"],
            "joined_via": "invite_token",
        }, identity)

    print("  Chain:     logged")

    # Step 6: Log to global chain
    append_to_chain("team_joined", {
        "team_hash": team_hash,
        "team_name": team_name,
        "role": payload["r"],
        "joined_via": "invite_token",
    })

    # Step 7: Network node scaffold (idempotent)
    from charter.network import load_node, create_node

    node = load_node()
    if not node:
        node = create_node(expertise=[], data_sources=[])
        print("  Node:      {} (created)".format(node.get("alias", "unknown")))
    else:
        print("  Node:      {} (existing)".format(node.get("alias", "unknown")))

    # Step 8: Update member count
    _update_team_manifest(team_hash)

    # Welcome
    print()
    print("Welcome to {}!".format(team_name))
    print("  Role:       {}".format(payload["r"]))
    print("  Team hash:  {}...".format(team_hash[:16]))
    print("  Invited by: {}...".format(payload["ib"][:16]))
    print()
    print("Next steps:")
    print("  charter team status        See your team")
    print("  charter identity           View your identity")
    print("  charter connect status     View your network node")
