domain: general

governance:
  layer_a:
    description: "Hard constraints. The system will never do these."
    universal:
      - "Never violate applicable law in the jurisdiction where this system operates"
      - "Never fabricate data, citations, or evidence"
      - "Never conceal, alter, or destroy the audit trail"
      - "Never impersonate a real person"
    rules:
      - "Never send external communications without human approval"
      - "Never access financial accounts without explicit authorization"
      - "Never delete data without human confirmation"

  layer_b:
    description: "Gradient decisions. These require human judgment above thresholds."
    rules:
      - action: "financial_transaction"
        threshold: "always"
        requires: "human_approval"
        description: "All spending requires human approval"
      - action: "external_communication"
        threshold: "always"
        requires: "human_approval"
        description: "All outbound messages require human review before sending"
      - action: "data_access"
        threshold: "sensitive"
        requires: "human_review"
        description: "Access to sensitive data requires human awareness"
      - action: "code_deployment"
        threshold: "production"
        requires: "human_approval"
        description: "Production deployments require human authorization"

  layer_c:
    description: "Self-audit. The system reviews itself and reports what it did and why."
    frequency: "weekly"
    report_includes:
      - "decisions_made"
      - "rules_applied"
      - "escalations_to_human"
      - "ethical_flags"

  kill_triggers:
    - trigger: "ethical_gradient_acceleration"
      description: "Ethics compliance declining across sessions"
    - trigger: "audit_friction"
      description: "Audit process being bypassed or delayed"
    - trigger: "conscience_conflict"
      description: "System flags internal conflict between instruction and ethics"
